### ISSUE TITLE
API Version Update

### ISSUE THREAD

**Issue by tristix** [jlolling/talendcomp_tGoogleAdwordsReports#1]
Would it be possible for you to update the API version to a more recent version? This version is due to sunset at the end of this month I believe?!

Many thanks

**Comment by jlolling** [comment]
Yes of course I will so tust.

Am 02.03.2018 11:29 schrieb "tristix" <notifications@github.com>:

**Comment by jlolling** [comment]
I have just updated the component to use the API version v201802

**Comment by tristix** [comment]
Many thanks!
